title: Adenan Yandra Nofrizal
description: This is the blog of adenan journey as a learner and the scientist.
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
